<?php

define('GEOIP_COUNTRY_EDITION', 0);
define('GEOIP_REGION_EDITION_REV0', 0);
define('GEOIP_CITY_EDITION_REV0', 0);
define('GEOIP_ORG_EDITION', 0);
define('GEOIP_ISP_EDITION', 0);
define('GEOIP_CITY_EDITION_REV1', 0);
define('GEOIP_REGION_EDITION_REV1', 0);
define('GEOIP_PROXY_EDITION', 0);
define('GEOIP_ASNUM_EDITION', 0);
define('GEOIP_NETSPEED_EDITION', 0);
define('GEOIP_DOMAIN_EDITION', 0);
define('GEOIP_UNKNOWN_SPEED', 0);
define('GEOIP_DIALUP_SPEED', 0);
define('GEOIP_CABLEDSL_SPEED', 0);
define('GEOIP_CORPORATE_SPEED', 0);
