<?php

define('INTL_MAX_LOCALE_LEN', 0);
define('IDNA_DEFAULT', 0);
define('IDNA_ALLOW_UNASSIGNED', 0);
define('IDNA_USE_STD3_RULES', 0);
define('IDNA_CHECK_BIDI', 0);
define('IDNA_CHECK_CONTEXTJ', 0);
define('IDNA_NONTRANSITIONAL_TO_ASCII', 0);
define('IDNA_NONTRANSITIONAL_TO_UNICODE', 0);
define('INTL_IDNA_VARIANT_2003', 0);
define('INTL_IDNA_VARIANT_UTS46', 0);
define('IDNA_ERROR_EMPTY_LABEL', 0);
