<?php

define('XSLT_OPT_SILENT', 0);
define('XSLT_SABOPT_PARSE_PUBLIC_ENTITIES', 0);
define('XSLT_SABOPT_DISABLE_ADDING_META', 0);
define('XSLT_SABOPT_DISABLE_STRIPPING', 0);
define('XSLT_SABOPT_IGNORE_DOC_NOT_FOUND', 0);
define('XSLT_SABOPT_FILES_TO_HANDLER', 0);
define('XSLT_ERR_UNSUPPORTED_SCHEME', 0);
