<?php

define('FRIBIDI_CHARSET_UTF8', 0);
define('FRIBIDI_CHARSET_8859_6', 0);
define('FRIBIDI_CHARSET_8859_8', 0);
define('FRIBIDI_CHARSET_CP1255', 0);
define('FRIBIDI_CHARSET_CP1256', 0);
define('FRIBIDI_CHARSET_ISIRI_3342', 0);
define('FRIBIDI_CHARSET_CAP_RTL', 0);
define('FRIBIDI_RTL', 0);
define('FRIBIDI_LTR', 0);
define('FRIBIDI_AUTO', 0);
