<?php

define('INGRES_ASSOC', 0);
define('INGRES_NUM', 0);
define('INGRES_BOTH', 0);
define('INGRES_EXT_VERSION', 'dummy');
define('INGRES_API_VERSION', 0);
define('INGRES_CURSOR_READONLY', 0);
define('INGRES_CURSOR_UPDATE', 0);
define('INGRES_DATE_MULTINATIONAL', 0);
define('INGRES_DATE_MULTINATIONAL4', 0);
define('INGRES_DATE_FINNISH', 0);
define('INGRES_DATE_ISO', 0);
define('INGRES_DATE_ISO4', 0);
define('INGRES_DATE_GERMAN', 0);
define('INGRES_DATE_MDY', 0);
define('INGRES_DATE_DMY', 0);
define('INGRES_DATE_YMD', 0);
define('INGRES_MONEY_LEADING', 0);
define('INGRES_MONEY_TRAILING', 0);
define('INGRES_STRUCTURE_BTREE', 0);
define('INGRES_STRUCTURE_CBTREE', 0);
define('INGRES_STRUCTURE_HASH', 0);
define('INGRES_STRUCTURE_CHASH', 0);
define('INGRES_STRUCTURE_HEAP', 0);
define('INGRES_STRUCTURE_CHEAP', 0);
define('INGRES_STRUCTURE_ISAM', 0);
define('INGRES_STRUCTURE_CISAM', 0);
