<?php

define('GUPNP_TYPE_BOOLEAN', 0);
define('GUPNP_TYPE_INT', 0);
define('GUPNP_TYPE_LONG', 0);
define('GUPNP_TYPE_DOUBLE', 0);
define('GUPNP_TYPE_FLOAT', 0);
define('GUPNP_TYPE_STRING', 0);
define('GUPNP_SIGNAL_DEVICE_PROXY_AVAILABLE', 0);
define('GUPNP_SIGNAL_DEVICE_PROXY_UNAVAILABLE', 0);
define('GUPNP_SIGNAL_SERVICE_PROXY_AVAILABLE', 0);
define('GUPNP_SIGNAL_SERVICE_PROXY_UNAVAILABLE', 0);
define('GUPNP_SIGNAL_ACTION_INVOKED', 0);
define('GUPNP_SIGNAL_NOTIFY_FAILED', 0);
define('GUPNP_SIGNAL_SUBSCRIPTION_LOST', 0);
define('GUPNP_CONTROL_ERROR_INVALID_ACTION', 0);
define('GUPNP_CONTROL_ERROR_INVALID_ARGS', 0);
define('GUPNP_CONTROL_ERROR_OUT_OF_SYNC', 0);
define('GUPNP_CONTROL_ERROR_ACTION_FAILED', 0);
