<?php

define('FILEINFO_NONE', 0);
define('FILEINFO_SYMLINK', 0);
define('FILEINFO_MIME_TYPE', 0);
define('FILEINFO_MIME_ENCODING', 0);
define('FILEINFO_MIME', 0);
define('FILEINFO_COMPRESS', 0);
define('FILEINFO_DEVICES', 0);
define('FILEINFO_CONTINUE', 0);
define('FILEINFO_PRESERVE_ATIME', 0);
define('FILEINFO_RAW', 0);
