<?php

define('CLASSKIT_ACC_PRIVATE', 0);
define('CLASSKIT_ACC_PROTECTED', 0);
define('CLASSKIT_ACC_PUBLIC', 0);
define('RUNKIT_IMPORT_FUNCTIONS', 0);
define('RUNKIT_IMPORT_CLASS_METHODS', 0);
define('RUNKIT_IMPORT_CLASS_CONSTS', 0);
define('RUNKIT_IMPORT_CLASS_PROPS', 0);
define('RUNKIT_IMPORT_CLASSES', 0);
define('RUNKIT_IMPORT_OVERRIDE', 0);
define('RUNKIT_ACC_PUBLIC', 0);
define('RUNKIT_ACC_PROTECTED', 0);
define('RUNKIT_ACC_PRIVATE', 0);
define('CLASSKIT_AGGREGATE_OVERRIDE', 0);
define('RUNKIT_VERSION', 'dummy');
define('CLASSKIT_VERSION', 'dummy');
