<?php

define('MYSQLND_MS_MASTER_SWITCH', 'dummy');
define('MYSQLND_MS_SLAVE_SWITCH', 'dummy');
define('MYSQLND_MS_LAST_USED_SWITCH', 'dummy');
define('MYSQLND_MS_QUERY_USE_MASTER', 0);
define('MYSQLND_MS_QUERY_USE_SLAVE', 0);
define('MYSQLND_MS_QUERY_USE_LAST_USED', 0);
define('MYSQLND_MS_QOS_CONSISTENCY_EVENTUAL', 0);
define('MYSQLND_MS_QOS_CONSISTENCY_SESSION', 0);
define('MYSQLND_MS_QOS_CONSISTENCY_STRONG', 0);
define('MYSQLND_MS_QOS_OPTION_GTID', 0);
define('MYSQLND_MS_QOS_OPTION_AGE', 0);
define('MYSQLND_MS_VERSION', 'dummy');
define('MYSQLND_MS_VERSION_ID', 0);
